// tests for add_user
// Generated by serverless-jest-plugin

const mod = require('../handler');

const jestPlugin = require('serverless-jest-plugin');

const { lambdaWrapper } = jestPlugin;
const attendance = lambdaWrapper.wrap(mod, { handler: 'attendance' });

const AWS = require('aws-sdk');

const attendance_item = {
    body: JSON.stringify({
        "event": "1234",
        "user_id": "testid",
        "online": true
    }),
};

describe('attendance', () => {
  it('Marks event attendance correctly', async () => await attendance.run(attendance_item).then(async (response) => {
    expect(response).toBeDefined();
    expect(response).toHaveProperty('statusCode', 200);
  }));
});
