'use strict';

// tests for add_sponsor_from_form
// Generated by serverless-jest-plugin

const jestPlugin = require('serverless-jest-plugin');
const fs = require("fs").promises;
const mod = require('./../handler');

const lambdaWrapper = jestPlugin.lambdaWrapper;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'add_sponsor_from_form' });

describe('add_sponsor_from_form', () => {
  beforeAll((done) => {
done();
  });

  it('adds the correct sponsor info into the database', () => {
    return fs.readFile('__tests__/inputs/typeform_response.json','utf8').then(responseForm => {
      const event = {body: responseForm};
      return wrapped.run(event).then((response) => {
        expect(response).toBeDefined();
        expect(response.statusCode).toBe(200);
        expect(response.body).toBeDefined();

        const responseBody = JSON.parse(response.body);
        expect(responseBody.downloadable_content[0].link).toBe("https://gotechnica.org/");
        expect(responseBody.footer_links[0].link).toBe("joblisting.com");
        expect(responseBody.footer_links[1].link).toBe("anotherListing.com");
        expect(responseBody.description).toBe("Technica is the world’s largest all-women and nonbinary hackathon");
        expect(responseBody.email_one).toBe("test@gmail.com");
        expect(responseBody.name).toBe("Technica");
        expect(responseBody.events_hosted.length).toBe(1);
        expect(responseBody.events_hosted[0]).toBe("Technica Event");
        expect(responseBody.prizes.length).toBe(1);
        expect(responseBody.prizes[0]).toBe("Technica prize");
      });
    })

  });

  it('form is missing answers', () => {
    return fs.readFile('__tests__/inputs/typeform_response2.json','utf8').then(responseForm => {
      const event = {body: responseForm};
      return wrapped.run(event).then((response) => {
        expect(response).toBeDefined();
        expect(response.statusCode).toBe(200);
        expect(response.body).toBeDefined();

        const responseBody = JSON.parse(response.body);
        expect(responseBody.downloadable_content[0].link).toBe("https://gotechnica.org/");
        expect(responseBody.email_one).toBe("test@gmail.com");
        expect(responseBody.name).toBe("Technica");
        expect(responseBody.events_hosted.length).toBe(1);
        expect(responseBody.events_hosted[0]).toBe("Technica Event");
        expect(responseBody.prizes.length).toBe(1);
        expect(responseBody.prizes[0]).toBe("Technica prize");
        expect(responseBody).not.toHaveProperty("description");
        expect(responseBody.footer_links).toHaveLength(0);
      });
    })

  });
});
